### ISSUE TITLE
vscode plugin seems broken with the current versions of other components

### ISSUE THREAD

**Issue by konste** [bazelbuild/vscode-bazel#153]
I try to use plugin version 0.3.0 with VSCode 1.40.1 and Bazel 1.2.0 on this trivial example: https://github.com/bazelbuild/examples/tree/master/cpp-tutorial/stage1 

When I try to debug //main:hello-world target Debugger does not stop on breakpoints and the Output window looks like the following:
```
[2019-11-25 11:16:21.147] [renderer1] [error] Command failed: bazel query 'kind(rule, //main:all)' --output=proto
Loading: 0 packages loaded
ERROR: invalid target format 'kind(rule, //main:all)': invalid package name 'kind(rule, //main': package names may not contain '//' path separators
Loading: 0 packages loaded
Loading: 0 packages loaded
: Error: Command failed: bazel query 'kind(rule, //main:all)' --output=proto
Loading: 0 packages loaded
ERROR: invalid target format 'kind(rule, //main:all)': invalid package name 'kind(rule, //main': package names may not contain '//' path separators
Loading: 0 packages loaded
Loading: 0 packages loaded

	at ChildProcess.exithandler (child_process.js:303:12)
	at ChildProcess.emit (events.js:200:13)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
[2019-11-25 11:16:22.077] [renderer1] [error] Command failed: bazel query 'kind(rule, //main:all)' --output=proto
Another command holds the client lock
Waiting for it to complete...
Loading: 0 packages loaded
ERROR: invalid target format 'kind(rule, //main:all)': invalid package name 'kind(rule, //main': package names may not contain '//' path separators
Loading: 0 packages loaded
Loading: 0 packages loaded
: Error: Command failed: bazel query 'kind(rule, //main:all)' --output=proto
Another command holds the client lock
Waiting for it to complete...
Loading: 0 packages loaded
ERROR: invalid target format 'kind(rule, //main:all)': invalid package name 'kind(rule, //main': package names may not contain '//' path separators
Loading: 0 packages loaded
Loading: 0 packages loaded

	at ChildProcess.exithandler (child_process.js:303:12)
	at ChildProcess.emit (events.js:200:13)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
[2019-11-25 11:16:41.964] [renderer1] [error] Cannot read property 'breakpoints' of undefined: TypeError: Cannot read property 'breakpoints' of undefined
	at d (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:397:159)
	at Object.t.convertToVSCPaths (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:397:409)
	at f.messageCallback (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:726:1000)
	at f.acceptMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:394:460)
	at f.handleData (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:398:293)
	at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:397:846)
	at Socket.emit (events.js:200:13)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)

```

**Comment by thomasvl** [comment]
Looking at the call stack, it seems like you might be failing on Windows?  If that correct?  Assuming that is true, can you try outside of the extension doing `bazel query 'kind(rule, //main:all)'` in that checkout?  Part of the error you are seeing seems to maybe be a bazel bug with `query` on Windows.

I'm not able to get any sorta issues like this running on a Mac.

**Comment by konste** [comment]
Yes, the problem happens on Windows. I have tried to run `bazel query 'kind(rule, //main:all)'` and got this result: ```ERROR: invalid target format 'kind(rule, //main:all)': invalid package name 'kind(rule, //main': package names may not contain '//' path separators``` Is it a bug in Bazel on Windows? Is it a known bug or shall I open one?

**Comment by thomasvl** [comment]
Does sound like a bug in bazel, but I don't know if it is known.  I'd suggest opening a issue in their tracker to have them check things out.

**Comment by konste** [comment]
Issue opened: https://github.com/bazelbuild/bazel/issues/10312

**Comment by thomasvl** [comment]
Thanks.  BTW - if this used to work in their 1.0 or 1.1, you might want to call it out as a regression.

**Comment by konste** [comment]
I have tried with 1.1 and 1.0 and Bazel behavior did not change, so it is not a regression.
Frankly I agree with @laszlocsomor that it should be much easier to change the plugin code to use double quotes on Windows than to change Bazel command line processing logic.
