### ISSUE TITLE
Bazel extension is confused by windows directory separators 

### ISSUE THREAD

**Issue by carpenterjc** [bazelbuild/vscode-bazel#239]
CodeLens doesn't work in packaged other than the root package. 
Bazel Build Targets doesn't work in Explorer view. 

Example of errors seen in `Log (Windows)`
```
: Error: Command failed: bazel --output_base=C:\Users\JAMESC~1\AppData\Local\Temp\456664b99c988a842f5af808d17c8c0f query kind(rule, //product\src:all) --output=proto
Loading: 0 packages loaded
ERROR: Error while parsing 'kind(rule, //product\src:all)': syntax error at '\src:all )'
Loading: 0 packages loaded
Loading: 0 packages loaded

	at ChildProcess.exithandler (child_process.js:317:12)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
```

getTargetsForBuildFile doesn't convert windows '\' to '/' when generating the bazel query command.

Visual Studio Code version: 1.56.0 and 1.57.1 
Bazel BUILD version: 0.4.1
```
 bazel version
Build label: 4.0.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jan 21 07:39:16 2021 (1611214756)
Build timestamp: 1611214756
Build timestamp as int: 1611214756
```

**Comment by cameron-martin** [comment]
Looks like this was fixed with #229
